env: "local"

connstring: "postgresql://postgres:postgres@localhost:5432/attendly?sslmode=disable"

jwtsecret: "SUPER-SECRET-CODE"

token_ttl: "1h"

grpc:
  address: "localhost:50051"
  timeout: "5s"

redis:
  addr: "localhost:6379"

migrationspath: "./migrations"
